### ISSUE TITLE
Cannot run on demo page

### ISSUE THREAD

**Issue by tungngovn** [Jianningli/MIA#2]
Hi, thanks for your work.
I can not run demo on the [Project demo website](http://studierfenster.icg.tugraz.at/skull_reconstruction/skull_reconstruction.html). When I tried to upload and reconstruct a .nrrd file of the SkullFix data, the progress bar stopped at 20% and nothing happened. Do you know how to solve this problem? Thank you.

**Comment by Jianningli** [comment]
Hi,
One possible reason is that the backend tried to 'denoise' the uploaded image (using connected component analysis) before the reconstruction. However, if the upload is already 'clean' i.e., contains only one single piece, the denoising codes will throw an error and the program would stopped running.

The skullfix images, as far as I know, are already cleaned before they are released.
best,

**Comment by tungngovn** [comment]
On the demo website, I can download only the defected skull model of the test case. So I cannot generate the implant because it lacks the healthy skull. Could you please send me the healthy skull model of your defected test case?

**Comment by Jianningli** [comment]
Hi,

The algorithm will generate the healthy skull given the defected skull as input. So in the second window you have to upload the same defected skull again and press 'reconstruct'. The reconstructed skull will be available on the second window. After that, you can generate the implant in the third window.  Sorry the workflow is a bit confusing. You can see our demo video here https://www.youtube.com/watch?v=pt-jw8nXzgs

best

**Comment by tungngovn** [comment]
Hi,
I just followed your instruction but the website stopped again at 40% while reconstructing the healthy skull.

**Comment by Jianningli** [comment]
Hi,

I tried and it also stopped at 40%. It worked some days ago though. I have asked the cloud adminstrator but haven't got a reply yet. I assume the problem is associated with a recent update of the clouds. Will get back to you when it returns to normal again.

best

**Comment by Jianningli** [comment]
> Hi, I just followed your instruction but the website stopped again at 40% while reconstructing the healthy skull.

Hi, the issue seems to be resolved now.

**Comment by tungngovn** [comment]
Thank you. I successfully run the demo.
